#!/usr/bin/env bash
# gatedefaults.sh — for each kernel gate, show how it parses getenv (default + value use).
cd /home/revn/strix-llama || exit 1
for g in LLAMA_MMB LLAMA_MMB_TALL LLAMA_MMB_SHADOW LLAMA_MMB_BF16W LLAMA_MMB_F32SPLIT LLAMA_MMB_GLU \
         LLAMA_MMB_DOWN16 LLAMA_MMB_CACHE LLAMA_MMB_MIN_T LLAMA_MMB_HC16 LLAMA_HC_BLK16 LLAMA_HC_GATEMIX \
         LLAMA_HC_MIX_FUSE LLAMA_HC_CN_SHAPE LLAMA_HC_RES16 LLAMA_HC_PACK_DI LLAMA_GDN_CHUNKED \
         LLAMA_GDN_CONV LLAMA_QSA_SPARSE LLAMA_QSA_BLOCK_SELECTION LLAMA_QSA_DENSE_SHORTCUT \
         LLAMA_QSA_DIRECT_INDICES LLAMA_QSA_FUSE_EXPAND LLAMA_QSA_PACK_KEYS LLAMA_QSA_PACK_VALUES \
         LLAMA_QSA_QUERY_STRIP LLAMA_QSA_SCORE_WMMA LLAMA_QSA_TOKEN_EMBD LLAMA_QSA_WHOLE_ATTN \
         LLAMA_NORM_GATED LLAMA_NORM_ROWS LLAMA_PLE_CONV LLAMA_PLE_PREFETCH LLAMA_MOE_RED_SCALAR \
         LLAMA_IDX_RELU_SUM LLAMA_MTP_QSA LLAMA_MTP_EH_FLATTEN; do
  hit=$(grep -rhE "getenv\(\"$g\"\)" ggml/src/ggml-cuda/ src/ 2>/dev/null | head -1 | sed 's/^ *//')
  printf '%-26s %s\n' "$g" "${hit:-(no direct getenv found)}"
done
